CREATE TABLE IF NOT EXISTS COLLECTION_ITEM
(
    ID UUID NOT NULL DEFAULT RANDOM_UUID() PRIMARY KEY,
    NAME VARCHAR(80)
);

CREATE TABLE IF NOT EXISTS ADDITIONAL_INFO
(
    ID UUID NOT NULL DEFAULT RANDOM_UUID() PRIMARY KEY,
    COLLECTION_ITEM UUID NOT NULL ,
    KEE VARCHAR(100), -- "KEY" IS A RESERVED WORD IN H2 DB
    VALUEE VARCHAR(100) -- "VALUE" IS A RESERVED WORD IN H2 DB
);

